# CompreFace configuration
# You can override any of these with -D system properties or environment variables.

COMPRE_FACE_BASE_URL=http://localhost:8000
COMPRE_FACE_API_KEY=7cd353a7-d91a-4fb0-8d73-38d16ff6f66e
COMPRE_FACE_SIMILARITY_THRESHOLD=0.92

