package services;

import entities.RappelHabitude;
import utils.MyDatabase;

import java.sql.*;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.*;

public class RappelHabitudeService {

    private final Connection cnx;

    public RappelHabitudeService() {
        cnx = MyDatabase.getInstance().getCnx();
    }

    // ===================== CRUD =====================

    public void ajouter(RappelHabitude r) throws SQLException {
        String sql = """
            INSERT INTO rappel_habitude (idHabitude, heureRappel, jours, actif, message, autoGenerated)
            VALUES (?, ?, ?, ?, ?, ?)
        """;
        try (PreparedStatement ps = cnx.prepareStatement(sql)) {
            ps.setInt(1, r.getIdHabitude());
            ps.setTime(2, Time.valueOf(r.getHeureRappel()));
            ps.setString(3, normalizeJours(r.getJours()));
            ps.setBoolean(4, r.isActif());
            ps.setString(5, r.getMessage());
            ps.setBoolean(6, r.isAutoGenerated());
            ps.executeUpdate();
        }
    }

    public List<RappelHabitude> rappelsActifsDuUser(int idU) throws SQLException {
        String sql = """
            SELECT r.*
            FROM rappel_habitude r
            JOIN habitude h ON h.idHabitude = r.idHabitude
            WHERE r.actif = 1 AND h.idU = ?
            ORDER BY r.heureRappel
        """;
        List<RappelHabitude> list = new ArrayList<>();
        try (PreparedStatement ps = cnx.prepareStatement(sql)) {
            ps.setInt(1, idU);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) list.add(map(rs));
            }
        }
        return list;
    }

    public void setActif(int idRappel, boolean actif) throws SQLException {
        String sql = "UPDATE rappel_habitude SET actif=? WHERE idRappel=?";
        try (PreparedStatement ps = cnx.prepareStatement(sql)) {
            ps.setBoolean(1, actif);
            ps.setInt(2, idRappel);
            ps.executeUpdate();
        }
    }

    public void supprimer(int idRappel) throws SQLException {
        String sql = "DELETE FROM rappel_habitude WHERE idRappel=?";
        try (PreparedStatement ps = cnx.prepareStatement(sql)) {
            ps.setInt(1, idRappel);
            ps.executeUpdate();
        }
    }

    // ===================== METIER D (smart reminders) =====================

    public RappelHabitude getAutoByHabitude(int idHabitude) throws SQLException {
        String sql = """
            SELECT *
            FROM rappel_habitude
            WHERE idHabitude = ? AND autoGenerated = 1
            ORDER BY idRappel DESC
            LIMIT 1
        """;
        try (PreparedStatement ps = cnx.prepareStatement(sql)) {
            ps.setInt(1, idHabitude);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return map(rs);
            }
        }
        return null;
    }

    // ✅ Vérification jours (déjà ok)
    public boolean rappelValideAujourdhui(RappelHabitude r, LocalDate date) {
        String today = jourFrancais(date);
        String jours = normalizeJours(r.getJours());
        if (jours.isEmpty()) return false;

        for (String j : jours.split(",")) {
            if (j.trim().equalsIgnoreCase(today)) return true;
        }
        return false;
    }

    // ===================== HELPERS =====================

    private static final Set<String> JOURS_VALIDES = Set.of("Lun","Mar","Mer","Jeu","Ven","Sam","Dim");

    private String normalizeJours(String jours) {
        if (jours == null) return "";

        jours = jours.replace(" ", "").trim();
        while (jours.contains(",,")) jours = jours.replace(",,", ",");
        if (jours.startsWith(",")) jours = jours.substring(1);
        if (jours.endsWith(",")) jours = jours.substring(0, jours.length() - 1);
        if (jours.isEmpty()) return "";

        LinkedHashSet<String> clean = new LinkedHashSet<>();
        for (String j : jours.split(",")) {
            if (JOURS_VALIDES.contains(j)) clean.add(j);
        }
        return String.join(",", clean);
    }

    private String jourFrancais(LocalDate d) {
        return switch (d.getDayOfWeek()) {
            case MONDAY -> "Lun";
            case TUESDAY -> "Mar";
            case WEDNESDAY -> "Mer";
            case THURSDAY -> "Jeu";
            case FRIDAY -> "Ven";
            case SATURDAY -> "Sam";
            case SUNDAY -> "Dim";
        };
    }

    private RappelHabitude map(ResultSet rs) throws SQLException {
        Time t = rs.getTime("heureRappel");
        LocalTime lt = (t == null) ? LocalTime.of(0, 0) : t.toLocalTime();

        return new RappelHabitude(
                rs.getInt("idRappel"),
                rs.getInt("idHabitude"),
                lt,
                rs.getString("jours"),
                rs.getBoolean("actif"),
                rs.getString("message"),
                rs.getBoolean("autoGenerated")
        );
    }
}